name: test-install
channels:
  - conda-forge
dependencies:
  - python=3.12
  - mpi4py
  - openmpi > 5
  - pip
  - pip:
    - "hnn_core[dev] @ git+https://github.com/jonescompneurolab/hnn-core.git"

variables:
  DYLD_FALLBACK_LIBRARY_PATH: $DYLD_FALLBACK_LIBRARY_PATH:$CONDA_PREFIX/lib
