name: hnn-core-env-noenvvars
channels:
  - conda-forge
dependencies:
  - python=3.12
  - mpi4py
  - openmpi > 5
  - pip
  - pip:
    # - "hnn_core[dev]==0.4rc4"
    - "hnn_core[dev] @ git+https://github.com/jonescompneurolab/hnn-core.git"
