{% set name = "hnn-core" %}
{% set version = "0.4.1" %}
{% set build_number = 0 %}

{% set python_inclusive_min = "3.12" %}
{% set python_exclusive_max = "3.13" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hnn_core-{{ version }}.tar.gz"
  sha256: 50c8ec5eea289b23e38b8f2be5643d117c13552a179d5eb7efd3d64224c9e537

build:
  skip: true  # [py<312 or py>313 or win or aarch64]
  entry_points:
    - hnn-gui=hnn_core.gui.gui:launch
  number: {{ build_number }}

requirements:
  host:
    - python >={{ python_inclusive_min }},<{{ python_exclusive_max }}
    - find-libpython
    - pip
    - setuptools >=40.8.0
    - ncurses >=6.5,<7.0a0
    - numpy >=1.19,<2
    - openmpi >=5.0.5,<6.0a0
    - mpi4py
    - readline >=8.2,<9.0a0
  run:
    - python >={{ python_inclusive_min }},<{{ python_exclusive_max }}
    - find-libpython
    - h5io
    - ipykernel
    - ipympl
    - ipython
    - ipywidgets >8.0.0
    - joblib
    - matplotlib-base >=3.5.3
    - psutil
    - scipy
    - voila
    - ncurses >=6.5,<7.0a0
    - numpy >=1.19,<2
    - openmpi >=5.0.5,<6.0a0
    - mpi4py
    - readline >=8.2,<9.0a0

test:
  imports:
    - hnn_core
  commands:
    - pip check
    - hnn-gui --help
  requires:
    - pip

about:
  summary: Code for biophysical simulation of a cortical column using Neuron
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asoplata
